### ISSUE TITLE
 Parse error: syntax error, unexpected end of file in /var/www/html/website/include/html_functions.php on line 143

### ISSUE THREAD

**Issue by mpahlevanzadeh** [adamdoupe/WackoPicko#5]
May be your php file doesn't work with new php or has problem without considering version.

**Comment by a1kaid** [comment]
make  line 69
      <?  change to  <?php 
then it works

**Comment by yangyangwithgnu** [comment]
first of all, README tells U, "First, ensure that short_open_tag PHP ini option is enabled". so, U can edit /etc/php5/apache2/php.ini (or something like that), find ```short_open_tag```, set it  ```short_open_tag = On```, and ```service apache2 restart```.
